---
title: "Earnings Calls Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
# Load packages.
library(tidyverse)
library(tidytext)
library(flexdashboard)
library(shiny)
library(rsconnect)

word_counts <- read_csv(here::here("Data", "word_counts.csv"))

revenue_sentiment <- read_csv(here::here("Data", "revenue_sentiment_apple.csv"))
```

Sidebar {.sidebar}
------------------------------------------

```{r}
# Select the company
# selectInput(
#   inputId = "company",
#   label = "Company",
#   choices = unique(call_data$company)
# )

# Select stop word lexicon
selectInput(
  inputId = "stopwords",
  label = "Stop Word Lexicon",
  choices = unique(word_counts$stopwords)
)


# Select number of words displayed
selectInput(
  inputId = "n_words",
  label = "Number of Words",
  choices = c(5, 10, 15, 20)
)

# Select start year
selectInput(
  inputId = "from_year",
  label = "From",
  choices = unique(word_counts$year)
)

# Select end year
selectInput(
  inputId = "to_year",
  label = "To",
  choices = unique(word_counts$year)
)

```


Row 
-----------------------------------------------------------------------

### Word Count by Year

```{r}
renderPlot({
  word_counts %>% 
    filter(stopwords==input$stopwords,
           year >= input$from_year,
           year <= input$to_year) %>% 
    group_by(year) %>% 
    slice(1:input$n_words) %>% 
    ungroup %>% 
    mutate(word = reorder_within(word, n, year)) %>%
    ggplot(aes(x = n, y = word)) +
    geom_col() +
    facet_wrap(~ year, scales="free") +
    scale_y_reordered()
})
```

Row 
-----------------------------------------------------------------------

### Overall Sentiment by Quarter since Q2 2002

```{r}
renderPlot({
  revenue_sentiment %>% 
    filter(year >= input$from_year,
           year <= input$to_year) %>% 
    ggplot(aes(x = period, y = sentiment_difference)) +
    geom_col()
})


```


### Revenue by Quarter since Q2 2002

```{r}
renderPlot({
  revenue_sentiment %>%
    filter(year >= input$from_year,
           year <= input$to_year) %>% 
    ggplot(aes(x = period, y = revenue)) +
    geom_col()
})

```




